# Generated by Django 6.0.2 on 2026-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('weightlifting', 'Weightlifting'), ('swimming', 'Swimming'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('other', 'Other')], help_text='Type of fitness activity', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=8, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Calories burned during activity', null=True)),
                ('date', models.DateField(help_text='Date of the activity')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
